- name: Update and upgrade apt packages
  command: apt update

- name: Install dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - libjansson-dev
    - gcc
    - make
    - policycoreutils
    - firewalld

- name: Install other dependencies
  shell: apt-get install libcurl4-nss-dev -y && apt-get install libcurl4-openssl-dev -y && apt-get install libcurl4-gnutls-dev -y && apt-get install libpam0g-dev -y

- name: Create a directory
  file:
    path: /home/genex/contrib
    state: directory
    mode: '0755'

- name: Clone opa repo
  ansible.builtin.git:
    repo: https://github.com/open-policy-agent/contrib
    dest: /home/genex/contrib


- name: Build the default target
  make:
    chdir: contrib/pam_opa/pam/

- name: copy to libsecurity
  command: cp /home/genex/contrib/pam_opa/pam/pam_opa.so /lib/x86_64-linux-gnu/security/

# - name: Put SELinux in permissive mode
#   selinux:
#     policy: targeted
#     state: permissive

- name: PAMD configuration file update
  template: src=roles/common-ubun/templates/sshd.j2
    dest=/etc/pam.d/sshd
    backup=yes
    owner=0 group=0 mode=0644

- name: sshd configuration file update
  template: src=roles/common-ubun/templates/sshd_config_ubuntu.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'

- name: DNS configuration
  template: src=roles/common-ubun/templates/hosts.j2
    dest=/etc/hosts
    backup=yes
    owner=0 group=0 mode=0644

- name: Creating an empty host identity
  file:
    path: "/etc/host_identity.json"
    state: touch

- name: hosts identity configuration
  template: src=roles/common-ubun/templates/host_identity.j2
    dest=/etc/host_identity.json
    backup=yes
    owner=0 group=0 mode=0644

- name: Restart service sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Stop service firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped

- name: Disable service firewalld
  command: systemctl disable firewalld


