---
- name: getcron output
  hosts: vault
  remote_user: genesisancheta
  become: yes
  gather_facts: no
  tasks:
    - shell: crontab -l > /tmp/output.txt && chown -R genesisancheta /tmp/output.txt 

- name: Verify output
  hosts: vault
  remote_user: genesisancheta
  gather_facts: no
  tasks:
    - shell: cat /tmp/output.txt
      register: cat_content_file
    - debug:
        msg: "{{ cat_content_file.stdout }}"